import { useState } from "react";
import axios from "axios";

export default function App() {
  const [prompt, setPrompt] = useState("");
    const [files, setFiles] = useState([]);
      const [logs, setLogs] = useState([]);
        const [loading, setLoading] = useState(false);

          const API = "https://your-backend.onrender.com"; // CHANGE THIS

            async function runAI() {
                if (!prompt) return;

                    setLoading(true);
                        setLogs(["🚀 Running AI..."]);

                            try {
                                  const res = await axios.post(`${API}/api/ai/run`, {
                                          prompt,
                                                  files,
                                                        });

                                                              const data = res.data;

                                                                    setLogs((prev) => [...prev, "🧠 " + data.explanation]);

                                                                          // Apply files
                                                                                if (data.files?.length) {
                                                                                        await axios.post(`${API}/api/ai/apply`, {
                                                                                                  files: data.files,
                                                                                                          });
                                                                                                                  setFiles(data.files);
                                                                                                                          setLogs((prev) => [...prev, "📁 Files applied"]);
                                                                                                                                }

                                                                                                                                      // Execute commands
                                                                                                                                            for (const cmd of data.commands || []) {
                                                                                                                                                    const exec = await axios.post(`${API}/api/ai/exec`, {
                                                                                                                                                              command: cmd,
                                                                                                                                                                      });

                                                                                                                                                                              setLogs((prev) => [
                                                                                                                                                                                        ...prev,
                                                                                                                                                                                                  `⚡ ${cmd}`,
                                                                                                                                                                                                            exec.data.stdout || exec.data.stderr,
                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                    setLogs((prev) => [...prev, "❌ Error: " + err.message]);
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                            setLoading(false);
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                    <div className="h-screen flex flex-col">

                                                                                                                                                                                                                                                          {/* TOP BAR */}
                                                                                                                                                                                                                                                                <div className="p-3 border-b border-gray-800 flex justify-between">
                                                                                                                                                                                                                                                                        <h1 className="font-bold">⚡ Quaro AI</h1>
                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                          onClick={runAI}
                                                                                                                                                                                                                                                                                                    className="bg-blue-600 px-4 py-1 rounded"
                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                      {loading ? "Running..." : "Run"}
                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                          {/* MAIN */}
                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-1 overflow-hidden">

                                                                                                                                                                                                                                                                                                                                                        {/* LEFT: FILES */}
                                                                                                                                                                                                                                                                                                                                                                <div className="w-1/4 border-r border-gray-800 p-2 overflow-auto">
                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-sm mb-2">Files</h2>
                                                                                                                                                                                                                                                                                                                                                                                    {files.map((f, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                <div key={i} className="text-xs mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                              📄 {f.path}
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* CENTER: EDITOR */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex-1 p-2 flex flex-col">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex-1 bg-gray-900 p-2 rounded"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Type your idea... e.g. Build a REST API"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={prompt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPrompt(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* RIGHT: TERMINAL */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="w-1/3 border-l border-gray-800 p-2 overflow-auto bg-black">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-sm mb-2">Terminal</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {logs.map((log, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={i} className="text-xs mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {log}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                